spring:
  datasource:
    url: jdbc:mysql://rm-uf6a4j4c62cwi194lbo.mysql.rds.aliyuncs.com:3306/wall_breaker_pro?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: poby_dev_root
    password: 89rc#e9E84&2UMe*ca8uRw
    driver-class-name: com.mysql.cj.jdbc.Driver

#server:
#  port: 8443
#  ssl:
#    key-store: cert/wallbreaker.pfx
#    key-store-password: AbqKt29v